# Generated by Django 5.0.1 on 2024-02-05 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_username_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='payments',
            old_name='data_of_payment',
            new_name='date_of_payment',
        ),
    ]
