# Generated by Django 5.0.1 on 2024-03-03 18:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_user_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='username',
        ),
    ]
